### ISSUE TITLE
Help trying to track down how clean URLs should be configured

### ISSUE THREAD

**Issue by timstallmann** [Daniel-KM/CleanUrl#5]
Hi! I've inherited an Omeka site & theme that someone else built but that we lost the DB to because of some bad backup management (before my time). So I'm trying to recreate the site config without a lot to go on. 

It looks like previously the site had links to that looked sort of like the links clean URL generates, except with everything lower-cased and spaces replaced with dashes. I tried installing the latest version of Clean URL and I get links with spaces in them, like `http://mcjc-omeka.l/Keith Edwards`, when what i want is `http://mcjc-omeka.l/keith-edwards` 

Am I missing an option to enable that? Do you have any insight into how the previous developer might have accomplished this?

**Comment by Daniel-KM** [comment]
Hi,

There is no option for lower case or to insert a dash.

The simpler is to generate the id you want as Dublin Core:Identifier for each item (eventually with a prefix, like : CleanUrl:), so here 

`CleanUrl: keith-edwards`

then set these options in the config page (the prefix and the element). 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by libmanuk** [comment]
Hey,

I am running 2.4.1 and can't seem to get this to work properly I have things set to use the DC:Identifier field.  I can get the prefix settings to work, but can't seem to get it to pick up the identifier.  Could this be an issue with the version of Omeka that I am using?

Thx.

--Eric

**Comment by Daniel-KM** [comment]
Hi,

I use this plugin with some 2.4.1 install without issue. What is the prefix you use?

To check an issue, I need the full config of the plugin and an example of an item.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
