### ISSUE TITLE
No Document Identifier

### ISSUE THREAD

**Issue by pashamkhan** [Daniel-KM/CleanUrl#6]
Clean URL seems like a very important plugin for my project. I have installed it and kept the default configuration, but my site is still displaying the default URLs, like

http://nmrashedarchive.com/document/294

instead of using the Dublin Core Identifier element, which should I think give the following URL:

http://nmrashedarchive.com/document/NMRArch-02-14-011-ai-samandar-handwritten

Each item has a unique identifier that has been imported from a spreadsheet using CSV import. You can look at the metadata for item #294 by clicking on the URL above, for instance, to verify this. But when I go into the Items view as admin, a "No document identifier" message appears. I have looked at the [closed issue relating to this](https://github.com/Daniel-KM/CleanUrl/issues/2) but it doesn't seem to help. Do let me know if you have any ideas. Thanks.

**Comment by Daniel-KM** [comment]
Hi,

This is probably a issue with the config. According to the metadata of the item 194, you should set:

- Field: Dublin Core Identifier
- Prefix of identifiers to use: let empty, without space (this is probably the issue)
- Default url of items: "/ generic / item identifier"
- Allowed urls for items: at least "/ generic / item identifier"
- Generic name to add before item identifier: "document/"

And other options as you want.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by pashamkhan** [comment]
Thanks so much. After I left the "Prefix of identifiers to use" field empty, the problem was solved. The default value in that field was "document:", which somehow did not work.

This is a very important plugin because it allows me to specify URLs algorithmically. Thank you for creating and maintaining it.

**Comment by Daniel-KM** [comment]
Hi,

Fine.
 
The prefix is useful when there are multiple identifiers, for example the call number, the url, an ark, a doi, or anything else. 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
