### ISSUE TITLE
Clean Url is an invalid plugin with Omeka 2.4.1

### ISSUE THREAD

**Issue by jrcwiok** [Daniel-KM/CleanUrl#8]
Hi,

I recently upgraded to Omeka 2.4.1 from Omeka 2.1.2 and the Clean Url is throwing the error that it is an invalid plugin. Any ideas for a work around? The AMNH Research Library is hosting a hackathon this weekend and this is throwing a huge wrench in the documentation needed for the programmers. Thanks! Jen

**Comment by jeremyboggs** [comment]
Looks like this issue was [resolved on the omeka-dev list](https://groups.google.com/forum/#!topic/omeka-dev/o5R_M45-ndg).

**Comment by Daniel-KM** [comment]
Hi,

I use it with Omeka 2.4.1 (and Omeka dev) and I don't see any issue. This is related to the installation. When you download a zip file from Github, you have to rename it and tochange rights.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
